var accountVerificationAddresses = [
  "Allen Street",
  "Ann Street",
  "Astor Place and Astor Row",
  "Barrow Street",
  "Bayard Street and Hester Street",
  "Beach Street",
  "Beak Street",
  "Beekman Place",
  "Bethune Street",
  "Bleecker Street",
  "Bogardus Place",
  "Bradhurst Avenue",
  "Broome Street",
  "Cabrini Boulevard",
  "Charles Street",
  "Charlton Street",
  "Christopher Street",
  "Colonel Robert Magaw Place",
  "Columbus Circle",
  "Cortlandt Street",
  "Delancey Street",
  "Detective Omar",
  "Dyckman Street",
  "Eldridge Street",
  "Forsyth Street",
  "Fulton Street",
  "Gay Street",
  "George Balanchine Way",
  "Great Jones Street",
  "Greene Street",
  "Henry Street",
  "Horatio Street",
  "Houston Street",
  "Irving Place",
  "Jane Street",
  "Jefferson Street",
  "Peter Jennings Way",
  "Juan Pablo Duarte Boulevard",
  "Lafayette Street",
  "LaGuardia Place",
  "Lenox Avenue",
  "Leonard Harper Way",
  "Leroy Street",
  "Ludlow Street",
  "Macdougal Street",
  "Madison Avenue and Madison Street",
  "Malcolm X Boulevard",
  "Mercer Street",
  "Monroe Street",
  "Morton Street",
  "Nassau Street",
  "Perry Street",
  "Rivington Street",
  "Rutgers Street",
  "St. Mark's Place",
  "Saint Nicholas Avenue",
  "Stuyvesant Street",
  "Sullivan Street",
  "Thompson Street",
  "Tiemann Place",
  "Vanderbilt Avenue",
  "Varick Street",
  "Vesey Street",
  "Washington Street",
  "Wooster Street",
  "Worth Street",
];

module.exports = {
    accountVerificationAddresses: accountVerificationAddresses
};
