export const USER_LOGIN_WITH_CREDS = "USER_LOGIN_WITH_CREDS";

export const USER_SIGNUP_WITH_CREDS = "USER_SIGNUP_WITH_CREDS";

export const USER_SIGNUP_WITH_GOOGLE = "USER_SIGNUP_WITH_GOOGLE";

export const USER_SIGNUP_WITH_FACEBOOK = "USER_SIGNUP_WITH_FACEBOOK";

export const USER_LOGOUT_WITH_CREDS = "USER_LOGOUT_WITH_CREDS";

export const LOAD_OFFER__LIST = "LOAD_OFFER__LIST";

export const LOAD_ACCOUNT_VERIFICATION_ADDRESSES = "LOAD_ACCOUNT_VERIFICATION_ADDRESSES";


export const GOOGLE_CLIENT_ID = '76223395153-gqihh4fo593uoqon1ahi7cgjos06lvr4.apps.googleusercontent.com';
export const FACEBOOK_APP_ID = '256502624819088';
